name: Docker Image

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
              with:
                  image: tonistiigi/binfmt:latest
                  platforms: all

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Generate Docker metadata
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: |
                      ghcr.io/podnoms/podnoms-backend
                  tags: |
                      type=ref,event=branch
                      type=semver,pattern={{version}}
                  flavor: |
                      latest=true

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              env:
                  DOCKER_BUILDKIT: 1
              with:
#                  platforms: linux/amd64,linux/arm64,linux/arm/v7
                  platforms: linux/amd64
                  push: true
                  file: docker/Dockerfile
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: Create Release
              id: create_release
              uses: actions/create-release@latest
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      ${{ steps.Changelog.outputs.changelog }}
                  draft: false
                  prerelease: false